name: earthlab
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab>=2.0.0,<3
  - numpy>=1.18.1
  - h5py
  - scipy>=1.3.0
  - dask=2.20.0
  - distributed=2.20.0
  - notebook
  - matplotlib
  - pandas>=1.0.1
  - pandas-datareader
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - pip:
    - gdown==3.14.0
  - xarray>=0.17.0
  - rioxarray


